# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/universal7880-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/universal7880-common/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/Data.msc:system/etc/firmware/Data.msc \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/bdwlan30.bin:system/etc/firmware/bdwlan30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/bdwlan32.bin:system/etc/firmware/bdwlan32.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/nvm_tlv_tf_1.1.bin:system/etc/firmware/nvm_tlv_tf_1.1.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/otp30.bin:system/etc/firmware/otp30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/qwlan30.bin:system/etc/firmware/qwlan30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/qwlan30_ibss.bin:system/etc/firmware/qwlan30_ibss.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/rampatch_tlv_tf_1.1.tlv:system/etc/firmware/rampatch_tlv_tf_1.1.tlv \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/utf30.bin:system/etc/firmware/utf30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/utfbd30.bin:system/etc/firmware/utfbd30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/utfbd32.bin:system/etc/firmware/utfbd32.bin \
    vendor/samsung/universal7880-common/proprietary/etc/nfc/sec_s3nrn81_rfreg.bin:system/etc/nfc/sec_s3nrn81_rfreg.bin \
    vendor/samsung/universal7880-common/proprietary/lib/hw/camera.vendor.exynos5.so:system/lib/hw/camera.vendor.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib/hw/sensors.universal7880.so:system/lib/hw/sensors.universal7880.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/universal7880-common/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/universal7880-common/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/universal7880-common/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/universal7880-common/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/universal7880-common/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/universal7880-common/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/universal7880-common/proprietary/lib/libtfa98xx.so:system/lib/libtfa98xx.so \
    vendor/samsung/universal7880-common/proprietary/lib/libuniapi.so:system/lib/libuniapi.so \
    vendor/samsung/universal7880-common/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/universal7880-common/proprietary/lib/modules/qca_cld/qca_cld_wlan.ko:system/lib/modules/qca_cld/qca_cld_wlan.ko \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/lib/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/camera.vendor.exynos5.so:system/lib64/hw/camera.vendor.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/gralloc.exynos5.so:system/lib64/hw/gralloc.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/sensorhubs.universal7880.so:system/lib64/hw/sensorhubs.universal7880.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/sensors.universal7880.so:system/lib64/hw/sensors.universal7880.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynoscamera.so:system/lib64/libexynoscamera.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynoscamera3.so:system/lib64/libexynoscamera3.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libExynosOMX_Core.so:system/lib64/libExynosOMX_Core.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libExynosOMX_Resourcemanager.so:system/lib64/libExynosOMX_Resourcemanager.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libfloatingfeature.so:system/lib64/libfloatingfeature.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libhwjpeg.so:system/lib64/libhwjpeg.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libsensorlistener.so:system/lib64/libsensorlistener.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libuniapi.so:system/lib64/libuniapi.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libuniplugin.so:system/lib64/libuniplugin.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Decoder.so:system/lib64/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:system/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Decoder.so:system/lib64/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Encoder.so:system/lib64/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:system/lib64/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.WMV.Decoder.so:system/lib64/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000030.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000030.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin:system/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/universal7880-common/proprietary/vendor/bin/hw/gpsd:system/vendor/bin/hw/gpsd \
    vendor/samsung/universal7880-common/proprietary/vendor/bin/mcDriverDaemon:system/vendor/bin/mcDriverDaemon \
    vendor/samsung/universal7880-common/proprietary/vendor/etc/gnss/ca.pem:system/vendor/etc/gnss/ca.pem \
    vendor/samsung/universal7880-common/proprietary/vendor/etc/Tfa9896.cnt:system/vendor/etc/Tfa9896.cnt \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/nfc/sec_s3nrn81_firmware.bin:system/vendor/firmware/nfc/sec_s3nrn81_firmware.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/setfile_3p8.bin:system/vendor/firmware/setfile_3p8.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/setfile_3p8_front.bin:system/vendor/firmware/setfile_3p8_front.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/hw/nfc_nci.default.so:system/vendor/lib/hw/nfc_nci.default.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libbauthserver.so:system/vendor/lib/libbauthserver.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libbauthtzcommon.so:system/vendor/lib/libbauthtzcommon.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libegis_fp_normal_sensor_test.so:system/vendor/lib/libegis_fp_normal_sensor_test.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libgf_in_system_lib.so:system/vendor/lib/libgf_in_system_lib.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libsynaFpSensorTestNwd.so:system/vendor/lib/libsynaFpSensorTestNwd.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libril.so:system/vendor/lib/libril.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/vendor.samsung.hardware.radio@1.0.so:system/vendor/lib/vendor.samsung.hardware.radio@1.0.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libwrappergps.so:system/vendor/lib/libwrappergps.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/hw/nfc_nci.default.so:system/vendor/lib64/hw/nfc_nci.default.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/hw/gps.default.so:system/vendor/lib64/hw/gps.default.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libbauthserver.so:system/vendor/lib64/libbauthserver.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libbauthtzcommon.so:system/vendor/lib64/libbauthtzcommon.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libegis_fp_normal_sensor_test.so:system/vendor/lib64/libegis_fp_normal_sensor_test.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libgf_in_system_lib.so:system/vendor/lib64/libgf_in_system_lib.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libsynaFpSensorTestNwd.so:system/vendor/lib64/libsynaFpSensorTestNwd.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libMcClient.so:system/vendor/lib64/libMcClient.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libMcRegistry.so:system/vendor/lib64/libMcRegistry.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libril.so:system/vendor/lib64/libril.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/vendor.samsung.hardware.radio@1.0.so:system/vendor/lib64/vendor.samsung.hardware.radio@1.0.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libwrappergps.so:system/vendor/lib64/libwrappergps.so

ifeq ($(WITH_EXYNOS_BSP),)
PRODUCT_COPY_FILES += \
    vendor/samsung/universal7880-common/proprietary/lib/hw/hwcomposer.exynos5.so:system/lib/hw/hwcomposer.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib/hw/memtrack.exynos5.so:system/lib/hw/memtrack.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosdisplay.so:system/lib/libexynosdisplay.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/universal7880-common/proprietary/lib/libfimg.so:system/lib/libfimg.so \
    vendor/samsung/universal7880-common/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/universal7880-common/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/universal7880-common/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/hwcomposer.exynos5.so:system/lib64/hw/hwcomposer.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/memtrack.exynos5.so:system/lib64/hw/memtrack.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libcsc.so:system/lib64/libcsc.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosdisplay.so:system/lib64/libexynosdisplay.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosgscaler.so:system/lib64/libexynosgscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosscaler.so:system/lib64/libexynosscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosutils.so:system/lib64/libexynosutils.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosv4l2.so:system/lib64/libexynosv4l2.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libfimg.so:system/lib64/libfimg.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libhdmi.so:system/lib64/libhdmi.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libhwcutils.so:system/lib64/libhwcutils.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libmpp.so:system/lib64/libmpp.so
endif

# Create Mali links for Vulkan and OpenCL
PRODUCT_PACKAGES += libGLES_mali

# Qualcomm WiFi driver
PRODUCT_PACKAGES += qca_cld_wlan
